/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsWalletsRouteImport } from './routes/products.wallets'
import { Route as ProductsTshirtsRouteImport } from './routes/products.tshirts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWalletsRoute = ProductsWalletsRouteImport.update({
  id: '/products/wallets',
  path: '/products/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTshirtsRoute = ProductsTshirtsRouteImport.update({
  id: '/products/tshirts',
  path: '/products/tshirts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/tshirts': typeof ProductsTshirtsRoute
  '/products/wallets': typeof ProductsWalletsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/tshirts': typeof ProductsTshirtsRoute
  '/products/wallets': typeof ProductsWalletsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/tshirts': typeof ProductsTshirtsRoute
  '/products/wallets': typeof ProductsWalletsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/tshirts' | '/products/wallets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/tshirts' | '/products/wallets'
  id: '__root__' | '/' | '/products/tshirts' | '/products/wallets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsTshirtsRoute: typeof ProductsTshirtsRoute
  ProductsWalletsRoute: typeof ProductsWalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/wallets': {
      id: '/products/wallets'
      path: '/products/wallets'
      fullPath: '/products/wallets'
      preLoaderRoute: typeof ProductsWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/tshirts': {
      id: '/products/tshirts'
      path: '/products/tshirts'
      fullPath: '/products/tshirts'
      preLoaderRoute: typeof ProductsTshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsTshirtsRoute: ProductsTshirtsRoute,
  ProductsWalletsRoute: ProductsWalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
